language: ruby
bundler_args: --without production
cache: bundler
sudo: false
rvm:
  - 2.3
jdk:
  - oraclejdk8
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
services:
  - redis-server
addons:
  chrome: stable
  apt:
    packages:
    - zlib1g-dev
    - libarchive-dev
before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
before_script:
  - cp ./config/secrets.yml.sample ./config/secrets.yml
  - RAILS_ENV=test bundle exec rails db:setup
  - mkdir tmp/solr-test
  - RAILS_ENV=test bundle exec solr_wrapper -v --config config/solr_wrapper_test.yml --version 5.5.5 &
  - RAILS_ENV=test bundle exec fcrepo_wrapper -v --config config/fcrepo_wrapper_test.yml --version 4.5.1 &
script:
  - bundle exec rails spec
