language: ruby
bundler_args: --without production
cache: bundler
sudo: false
rvm:
  - 2.3
jdk:
  - oraclejdk8
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
services:
  - redis-server
addons:
  chrome: stable
  apt:
    packages:
    - zlib1g-dev
    - libarchive-dev
before_install:
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &
before_script:
  - cp ./config/secrets.yml.sample ./config/secrets.yml
script:
  - bundle exec rails spec
